# Directory and file filters
included:
  - Plugins
  - Source
  - Tests
  - Package.swift
excluded:
  - Tests/BuiltInRulesTests/Resources
  - Tests/FrameworkTests/Resources

# Enabled/disabled rules
analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
    - missing_docs
